@url=http://47.106.122.35:9900
@json=Content-Type: application/json 

POST {{url}}user/userList
{{json}}

{
    "page":"1",
    "numOfPage":"3"
}
###
POST {{url}}user/queryByUserName
{{json}}

{
    "userName":"xw"
}


###
POST {{url}}user/addUser
{{json}}

{
    "userName":"super1",
    "password":"123456",
    "email":"11527@qq.com",
    "testYear":"2020",
    "goalSchool":"杭州师范大学"
}

###
POST  {{url}}user/deleteUser
{{json}}

{
    "userId":"41"
}

###
POST  {{url}}login
{{json}}

{
    "userName":"xwy",
    "password":"123456"
}

### 推送
POST  {{url}}info/infoList
{{json}}

{
    "page":"1",
    "numOfPage":"4"
}
### 推送根据标题查询
POST  {{url}}info/queryByInfoTitle
{{json}}

{
    "infoTitle":"杭"
}

